theme: jekyll-theme-minimal
description: I am a graduate student at Texas Tech University and an aspiring data scientist. This portfolio is a collection of Kaggle competitions, side projects, and school projects which I have completed using data analytics and machine learning methods. 
logo: EdJWang.github.io/Pictures/Profile_img.jpg
